import QtQuick
import QtMultimedia

Item {
  id:cameraRoot;property var renderer:null;property alias camera:nativeCamera;property int handledCommandRevision:-1
  function deviceValid(){var requested=String(renderer?renderer.prop("camera_device",""):"");if(requested==="")return true;var list=mediaDevices.videoInputs;for(var i=0;i<list.length;i++)if(String(list[i].id)===requested||list[i].description===requested)return true;if(renderer)renderer.componentError("camera_device_not_found","The declared camera device does not exist",{device:requested});return false}
  function device(){var requested=String(renderer?renderer.prop("camera_device",""):"");var list=mediaDevices.videoInputs;if(requested==="")return mediaDevices.defaultVideoInput;for(var i=0;i<list.length;i++)if(String(list[i].id)===requested||list[i].description===requested)return list[i];return null}
  function focusMode(){var value=String(renderer?renderer.prop("focus_mode","auto"):"auto");if(value==="auto_near")return Camera.FocusModeAutoNear;if(value==="auto_far")return Camera.FocusModeAutoFar;if(value==="hyperfocal")return Camera.FocusModeHyperfocal;if(value==="infinity")return Camera.FocusModeInfinity;if(value==="manual")return Camera.FocusModeManual;return Camera.FocusModeAuto}
  function flashMode(){var value=String(renderer?renderer.prop("flash_mode","auto"):"auto");if(value==="off")return Camera.FlashOff;if(value==="on")return Camera.FlashOn;return Camera.FlashAuto}
  function torchMode(){var value=String(renderer?renderer.prop("torch_mode","off"):"off");if(value==="on")return Camera.TorchOn;if(value==="auto")return Camera.TorchAuto;return Camera.TorchOff}
  function exposureMode(){var value=String(renderer?renderer.prop("exposure_mode","auto"):"auto");var modes={manual:Camera.ExposureManual,portrait:Camera.ExposurePortrait,night:Camera.ExposureNight,sports:Camera.ExposureSports,snow:Camera.ExposureSnow,beach:Camera.ExposureBeach,action:Camera.ExposureAction,landscape:Camera.ExposureLandscape,night_portrait:Camera.ExposureNightPortrait,theatre:Camera.ExposureTheatre,sunset:Camera.ExposureSunset,steady_photo:Camera.ExposureSteadyPhoto,fireworks:Camera.ExposureFireworks,party:Camera.ExposureParty,candlelight:Camera.ExposureCandlelight,barcode:Camera.ExposureBarcode};return modes[value]===undefined?Camera.ExposureAuto:modes[value]}
  function whiteBalanceMode(){var value=String(renderer?renderer.prop("white_balance_mode","auto"):"auto");var modes={manual:Camera.WhiteBalanceManual,sunlight:Camera.WhiteBalanceSunlight,cloudy:Camera.WhiteBalanceCloudy,shade:Camera.WhiteBalanceShade,tungsten:Camera.WhiteBalanceTungsten,fluorescent:Camera.WhiteBalanceFluorescent,flash:Camera.WhiteBalanceFlash,sunset:Camera.WhiteBalanceSunset};return modes[value]===undefined?Camera.WhiteBalanceAuto:modes[value]}
  function send(name,payload){if(renderer&&renderer.subscribed(name))renderer.bridge.sendEvent(renderer.surfaceName,renderer.controlId,name,payload||{})}
  function command(){if(!renderer)return;var revision=Number(renderer.prop("command_revision",0));if(revision===handledCommandRevision)return;handledCommandRevision=revision;var value=String(renderer.prop("command",""));if(value==="start")nativeCamera.start();else if(value==="stop")nativeCamera.stop()}
  MediaDevices{id:mediaDevices}
  Camera{id:nativeCamera;cameraDevice:cameraRoot.device();active:renderer&&renderer.prop("active",false)===true&&cameraRoot.deviceValid();focusMode:cameraRoot.focusMode();flashMode:cameraRoot.flashMode();torchMode:cameraRoot.torchMode();exposureMode:cameraRoot.exposureMode();exposureCompensation:Number(renderer?renderer.prop("exposure_compensation",0):0);manualIsoSensitivity:Number(renderer?renderer.prop("iso",-1):-1);manualExposureTime:Number(renderer?renderer.prop("shutter_speed",-1):-1);whiteBalanceMode:cameraRoot.whiteBalanceMode();colorTemperature:Number(renderer?renderer.prop("color_temperature",0):0);zoomFactor:Number(renderer?renderer.prop("zoom_factor",1):1);onActiveChanged:{cameraRoot.send(active?"start":"stop",{});cameraRoot.send("active_change",{value:active})} onFocusModeChanged:cameraRoot.send("focus",{mode:focusMode,distance:focusDistance});onExposureModeChanged:cameraRoot.send("exposure",{mode:exposureMode,compensation:exposureCompensation,iso:isoSensitivity,shutter_speed:exposureTime});onErrorOccurred:function(error,errorString){renderer.componentError("camera_failed",errorString,{native_code:error})}}
  Component.onCompleted:command();Connections{target:renderer;function onNodeChanged(){cameraRoot.command()}}
}
