import QtQuick
import Qt.labs.folderlistmodel

Item {
  id:folderRoot;property var renderer:null;property alias model:nativeModel
  function sortField(){var value=String(renderer?renderer.prop("sort_field","name"):"name");if(value==="time")return FolderListModel.Time;if(value==="size")return FolderListModel.Size;if(value==="type")return FolderListModel.Type;if(value==="unsorted")return FolderListModel.Unsorted;return FolderListModel.Name}
  function entries(){var result=[];for(var i=0;i<nativeModel.count;i++)result.push({name:nativeModel.get(i,"fileName"),base_name:nativeModel.get(i,"fileBaseName"),url:String(nativeModel.get(i,"fileUrl")),path:nativeModel.get(i,"filePath"),size:nativeModel.get(i,"fileSize"),modified:String(nativeModel.get(i,"fileModified")),is_dir:nativeModel.get(i,"fileIsDir")});return result}
  FolderListModel{id:nativeModel;folder:renderer?renderer.assetUrl(renderer.prop("folder","")):"";rootFolder:renderer?renderer.assetUrl(renderer.prop("root_folder","")):"";nameFilters:renderer?renderer.prop("name_filters",[]):[];showFiles:!renderer||renderer.prop("show_files",true)!==false;showDirs:!renderer||renderer.prop("show_dirs",true)!==false;showDirsFirst:!renderer||renderer.prop("show_dirs_first",true)!==false;showDotAndDotDot:renderer&&renderer.prop("show_dot_and_dot_dot",false)===true;showHidden:renderer&&renderer.prop("show_hidden",false)===true;showOnlyReadable:!renderer||renderer.prop("show_only_readable",true)!==false;sortField:folderRoot.sortField();sortReversed:renderer&&renderer.prop("sort_reversed",false)===true;caseSensitive:renderer&&renderer.prop("case_sensitive",false)===true;onCountChanged:if(renderer){renderer.bridge.sendEvent(renderer.surfaceName,renderer.controlId,"count_change",{value:count});renderer.bridge.sendEvent(renderer.surfaceName,renderer.controlId,"change",{values:folderRoot.entries()})} onFolderChanged:if(renderer)renderer.bridge.sendEvent(renderer.surfaceName,renderer.controlId,"folder_change",{value:String(folder),parent:String(parentFolder)});onStatusChanged:if(renderer)renderer.bridge.sendEvent(renderer.surfaceName,renderer.controlId,"status",{value:status})}
}
